call python -m pip install flask
call python -m pip install flask-login
call python -m pip install flask-openid
call python -m pip install flask-mail
call python -m pip install flask-sqlalchemy
call python -m pip install sqlalchemy-migrate
call python -m pip install flask-whooshalchemy
call python -m pip install flask-wtf
call python -m pip install flask-babel
call python -m pip install guess_language
call python -m pip install flipflop
call python -m pip install coverage