call Scripts\pip install flask
call Scripts\pip install flask-login
call Scripts\pip install flask-openid
call Scripts\pip install flask-mail
call Scripts\pip install flask-sqlalchemy
call Scripts\pip install sqlalchemy-migrate
call Scripts\pip install flask-whooshalchemy
call Scripts\pip install flask-wtf
call Scripts\pip install flask-babel
call Scripts\pip install guess_language
call Scripts\pip install flipflop
call Scripts\pip install coverage