from QueryStock import QueryStock, BaseDatos

import urllib2
import urllib
import codecs
folder='E:\\virtualenv\\Quanto_Backend\\Quanto\\stocks\\'


folder2='E:\\virtualenv\\Quanto_Backend\\Quanto\\stocks\\'


stocks=["AA","AAPL","AAXJ","ABT","ACWI","ACWX","ADP","AESGENER","AFPCAPITAL","AGRICULTOR","AGUAS-A","AGUAS-B","AGUNSA","AIG","AKOA-CL","AKOB-CL","ALMENDRAL","AMGN","AMZN","ANASAC","ANDACOR","ANDINA-A","ANDINA-B","ANTARCHILE","AQUACHILE","ATSA","AUSTRALIS","AVP","AXP","AXXION","BA","BAC","BANMEDICA","BANVIDA","BBVACL","BCI","BESALCO","BICECORP","BIIB","BKF","BLUMAR","BRF","BSANTANDER","BTU","C","CALICHERAA","CALICHERAB","CAMANCHACA","CAMPOS","CANALISTAS","CAP","CAROZZI","CARVILE","CASABLANCA","CASGEN","CAT","CCT","CCU","CDCRAIG-A","CDCRAIG-B","CEM","CEMENTOS","CENCOSUD","CFMITNIPSA","CFR","CGE","CGEDISTRO","CHILE","CHILECTRA","CHOLGUAN","CIC","CINTAC","CLUBCAMPO","CLUBUNION","CMCSA","CMPC","COLBUN","COLCRAIG-A","COLCRAIG-B","COLINSE","COLOCOLO","COLOSO","COLX","COMERCIO","CONCHATORO","CONSOGRAL","COPEC","COPEVAL","CORPBANCA","CORPESCA","COST","COUNTRY-A","COUNTRY-B","COUNTRY-P","COVADONGA","CPK","CRAIGHOUSE","CRISTALES","CRUZADOS","CRUZBLANCA","CSCO","CTC-A","CTC-B","CTC-MUNDO","CTISA","CU-CL","CUPRUM","CVA","CVS","CVX","DD","DEHESA","DETROIT","DIS","DTV","DUNCANFOX","EBAY","ECH","ECL","ECNS","EDELMAG","EDELPA","EEM","EFA","EGPT","EIDO","EIRL","EIS","EISA","ELECDA","ELECDA-SD","ELECMETAL","ELIQSA","ELIQSA-SD","EMAG","EMBONOR-A","EMBONOR-B","EMC","EMELARI","EMELARI-SD","EMILIANA","EMLC","ENACAR","ENAEX","ENDESA","ENDESPAN","ENERSIS","ENJOY","ENLASA","ENTEL","ENZL","EPERVA","EPHE","EPOL","EPP","EPU","ERUS","ESPANA","ESPANOLA","ESPANOLVAL","ESR","ESRX","ESSAL-A","ESSAL-B","ESSBIO-A","ESSBIO-B","ESSBIO-C","ESTACIONAM","ESVAL-A","ESVAL-B","ESVAL-C","EWA","EWC","EWG","EWH","EWI","EWJ","EWL","EWM","EWN","EWP","EWQ","EWS","EWT","EWU","EWW","EWY","EWZ","EWZS","EZA","EZU","FALABELLA","FASA","FB","FCX","FEPASA","FERIAOSOR","FORUS","FOSFOROS","FROWARD","FXI","GASCO","GDX","GDXJ","GE","GENERADORA","GERJ","GEX","GILD","GOLF","GOOGL","GPK","GRANADILLA","GRANGE-A","GRANGE-B","HABITAT","HAL","HAP","HD","HF","HIPERMARC","HIPICO","HIPODROMOA","HIPODROMOB","HITES","HON","HORNOS","HPQ","HYG","IACSA","IAM","IANSA","IAU","IBM","IDU","IDX","IEV","ILC","ILF","INDISA","INDIVER","INDY","INFODEMA","INGEVEC","INMOBVINA","INTASA","INTC","INTEROCEAN","INVERCAP","INVERFOODS","INVERMAR","INVERNOVA","INVEXANS","INVIESPA","IPAL","IQUIQUE","ISANPA","ITB","IVE","IVV","IVW","IWB","IWC","IWD","IWF","IWM","IWN","IWO","IWP","IWR","IWS","IWV","IXC","IXG","IYC","IYE","IYF","IYJ","IYK","IYM","IYR","IYW","IYZ","JNJ","JPM","KO","KOL","LAN","LASCONDES","LATM","LEASNAC","LFL-CL","LINDEFUT","LITORAL","LNKD","LQD","MAISONNETT","MARBELLACC","MARINSA","MASISA","MCD","MCHI","MDLZ","MELON","MINERA","MMM","MO","MOLLER","MOLYMET","MOO","MRK","MS","MSFT","MUELLES","MULTIFOODS","MXI","NAVARINO","NAVIERA","NEM","NIBSA","NITRATOS","NKE","NLR","NORTEGRAN","NUEVAPOLAR","NUEVAREG","OLDBOYS","ORCL","OROBLANCO","PACIFICO","PARAUCO","PASUR","PAZ","PCLN","PEHUENCHE","PEK","PEP","PFE","PG","PILMAIQUEN","PLANVITAL","PLND","POLO","POLPAICO","POTASIOS-A","POTASIOS-B","PREVISION","PROVIDA","PUCOBRE-A","PUCOBRE-C","PUCOBRE-D","PUERTO","PUNTILLA","PUYEHUE","QCOM","QUEMCHI","QUILICURA","QUINENCO","REBRISA-A","REBRISA-B","REMX","RIPLEY","RSX","RSXJ","SALFACORP","SANPEDRO","SANTARITA","SANTANA","SANTANGRUP","SBUX","SCHWAGER","SCIF","SCJ","SCZ","SECURITY","SHV","SHY","SIEMEL","SINTEX","SIPSA","SIXTERRA","SK","SLV","SLX","SM-CHILEA","SM-CHILEB","SM-CHILED","SM-CHILEE","SMSAAM","SOCOVESA","SOFRUCO","SONDA","SOPROCAL","SOQUICOM","SPLS","SPORTFRAN","SPORTING","SQM-A","SQM-B","STADITALIA","SUDAMER-A","T","TATTERSALL","TECHPACK","TELSUR","TGT","THD","TIP","TRICAHUE","TRV","TUR","TXN","UNESPA","UNH","UNIONGOLF","UNP","UPS","USB","UTX","V","VALORES","VAPORES","VCMAC1","VCMBC1","VENTANAS","VICONTO","VNM","VOLCAN","VZ","WATTS","WFC","WMT","WMTCL","X","XOM","YHOO","YUGOSLAVA","ZOFRI"]



if __name__ == "__main__":
    print "Inicio"
    indice = 0

    bd = BaseDatos()
    qs = QueryStock()
    print "instancia OK"
#    archivoStock = open(folder + 'listadoIPSA.dat')
#    splitLines = archivoStock.read().split('\n')
#    archivoStock.close

    for nemo in stocks:
        indice +=1
        print indice, nemo


    #    bd.traeStockBCSHistorico(nemo)
    #bd.cargaArchivoAtablaOHLCV( nemo )
        qs.procesaNemo(nemo,"20100101", "20141012")


